module.exports = function () {

    //grab the list
    const Todo = require('./utils/TodoList')

    //fill the todoList
    Todo.setStatusColor('Done', 'green')
    Todo.setStatusColor('In Progress', 'yellow')
    Todo.setStatusColor('Not Started', 'red')
    Todo.setStatusColor('Canceled', 'blue')
    Todo.setStatusColor('Not Applicable', 'magenta')
    Todo.addItem('Setup Electron', 'Done')
    Todo.addItem('Link Github', 'Done')
    Todo.addItem('Setup the RUNE system', 'Not Started')
    Todo.addItem('Add todoList', 'Done')
    Todo.addItem('Make the browser stay on top of the screen', 'Done')
    Todo.addItem('Make the browser invisible', 'Done')
    Todo.addItem('Add key inputs', 'Not Started')
    Todo.addItem('Add mouse inputs', 'Not Started')
    Todo.addItem('Create the renderstack module', 'Done')
    Todo.addItem('Add the Color module', 'Done')
    Todo.addItem('Add the MoreMath module', 'Done')
    Todo.addItem('Create a renderstack function for the node side', 'Done')
    Todo.addItem('Make the renderstack only render when needed', 'Not Started')
    Todo.addItem('Add many render layers', 'Not Started')
    Todo.addItem('Make the new layers have names', 'Not Started')
    Todo.addItem('Give the new layers a z index', 'Not Started')
    Todo.addItem('Turn the project into an application', 'Not Started')
    Todo.addItem('Make the project auto publish the application', 'Not Started')
    Todo.addItem('Orginize the project', 'Done')
    Todo.addItem('Add comments to everything', 'Done')
    Todo.addItem('Hide the electron icon', 'Done')
    Todo.addItem('Make the electron project auto start', 'Not Started')
    Todo.addItem('Make the browser fill the screen', 'Done')
    Todo.addItem('Switch to the new github', 'Done')
    Todo.addItem('Make the node side die if the browser does', 'Done')
    Todo.addItem('Give the browser a .js file', 'Done')
    Todo.addItem('Add canvas to the browser', 'Done')
    Todo.addItem('Make the canvas always fill the screen', 'Done')
    Todo.addItem('Let the mouse / key inputs go thru the browser', 'Done')
    Todo.addItem('Hide the bar at the top of the browser', 'Done')
    Todo.addItem('Create the acronym for MAGE', 'Done')
    Todo.addItem('Create functions to talk node to browser', 'Done')
    Todo.addItem('Create functions to talk browser to node', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Fill Rect', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Line Rect', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Fill Circle', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Line Cirle', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Glowing', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Gradients', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Fill Complex shapes', 'Done')
    Todo.addItem('Add feature to the renderstack modue: Line Complex shapes', 'Done')
    Todo.addItem('Create a bridge to go from browser to node, and vice versa', 'Done')
    Todo.addItem('Add the runes', 'Not Started')
    Todo.addItem('Create a good name for the runes', 'Not Started')
    Todo.addItem('Sandbox the runes', 'Not Started')
    Todo.addItem('Create a hub for all the runes', 'Not Started')
    Todo.addItem('Create a good name for the hub for runes', 'Not Started')
    Todo.addItem('Give the hub wesite a nice gui', 'Not Started')
    Todo.addItem('Give the hub site apis for MAGE', 'Not Started')
    Todo.addItem('Add a way to upload RUNES on the webpage', 'Not Started')
    Todo.addItem('Get rid of the bridge', 'Canceled')
    Todo.addItem('Add an api for clicking', 'Not Started')
    Todo.addItem('Add an api for typing', 'Not Started')
    Todo.addItem('Add an api for mouse movement', 'Not Started')
    Todo.addItem('Add an api for reading the screen', 'Not Started')
    Todo.addItem('Create a RUNE for managing other RUNEs', 'Not Started')
    Todo.addItem('Make a better colors module', 'Done')
    Todo.addItem('Make a todolist module that uses files to store the list', 'Done')
    Todo.addItem('Pass key inputs to the RUNEs', 'Not Started')
    Todo.addItem('Pass mouse inputs to the RUNEs', 'Not Started')
    Todo.addItem('Make require work on the browser side', 'Canceled')
    Todo.addItem('Add a debug mode for the browser', 'Done')
    Todo.addItem('Make the Renderstack have some kind of scaling options', 'Not Started')
    Todo.addItem('Make Renderstack gradients x/y relitive to the main object', 'Done')
    Todo.addItem('Make the Renderstack have autocomplete for the objects', 'Not Started')
    Todo.addItem('Make the Renderstack rotation args fit to the rest of the system (r0=up,r1/4=right)', 'Not Applicable')
    Todo.addItem('Create a module for the Renderstack that adds compound shapes', 'Not Started')
    Todo.addItem('Create a module for the Renderstack to add animations', 'Not Started')
    Todo.addItem('Fix the Color module to use object setters', 'Not Started')
    Todo.addItem('Add a module for creating GUIs with the Renderstack', 'Not Started')
    Todo.addItem('Add TLDR to the Todo module', 'Done')
    Todo.addItem('Made errors on the browser go to the node console', 'Done')
    Todo.addItem('Add curved lines to the Renderstack', 'In Progress')
    Todo.addItem('Add clearrects to the Renderstack', 'Done')
    Todo.addItem('Add cliping to the Renderstack', 'Not Started')
    Todo.addItem('Add rotation to the Renderstack drawing', 'Canceled')
    Todo.addItem('Add a way to count the number of lines of code I have written in this file', 'Done')
    Todo.addItem('Add text to the Renderstack', 'Done')
    Todo.addItem('Combine the Renderstack, Complex shapes, and Animations all together as one module', 'Not Started')
    Todo.addItem('Add fonts for the Renderstack text', 'Done')
    Todo.addItem('Make the text wrap in a box', 'Not Applicable')
    Todo.addItem('Add line caps', 'Done')
    Todo.addItem('Pass the screen size to the node side when it updates', 'Done')
    Todo.addItem('Add line joins', 'Done')
    Todo.addItem('Add text options to the Renderstack', 'Done')
    Todo.addItem('Make console.log from browser redirect to the node side', 'Done')
    Todo.addItem('Add layers to the Renderstack', 'Done')
    Todo.addItem('Add layers to complex shapes', 'Not Started')
    Todo.addItem('Add a clear screen option to Renderstack', 'Done')
    Todo.addItem('Add comments to the Renderstack module', 'Not Started')
    Todo.addItem('Turn all the startup logging its own file', 'Done')
    Todo.addItem('Make the project push to github everytime the todolist gets an item completed', 'Done')
    Todo.addItem('Make a function to print things in order', 'Canceled')
    Todo.addItem('Give each rune its own renderstack', 'Done')
    Todo.addItem('Add a function to set a runes renderstack', 'Done')
    Todo.addItem('Clump the line counter, github pusher, and todolist in one module', 'Done')
    Todo.addItem('Add advanced paths to the Renderstack, with curves', 'In Progress')
    Todo.addItem('Fix github so its pushing from my acc', 'Done')
    Todo.addItem('Fix the Renderstack so it only applies things when needed', 'Not Started')

    Todo.fullLogAndPush(
        { infoColor: 'white' },
        [
            './browser/index.html',
            './browser/Renderstack.js',
            './browser/script.js',
            './utils/Colors.js',
            './utils/Misc.js',
            './utils/MoreMath.js',
            './main-node.js',
            './package.json',
            './preload.js',
            './setup-node.js',
            './startup-logs.js',
            './oldTodo.json'
        ])
}